[21322] Support for `Fast DDS 3.0`
eProsima/rmw_fastrtps pull request #32
Opened 2024-08-29 13:47 UTC by Mario-DL

Related branches to this PR:

* [rosidl_typesupport_fastrtps - feature/support-fastdds-3.0](https://github.com/eProsima/rosidl_typesupport_fastrtps/tree/feature/support-fastdds-3.0)
* [rosidl_dynamic_typesupport_fastrtps - feature/support-fastdds-3.0](https://github.com/eProsima/rosidl_dynamic_typesupport_fastrtps/tree/feature/support-fastdds-3.0)
* ROS 2 jazzy over Ubuntu 24.04

This PR adds support for `Fast DDS 3.0`  to `rmw_fastrtps_shared_cpp`, `rmw_fastrtps_cpp` and `rmw_fastrtps_dynamic_cpp`.

~~[demo_nodes_cpp](https://github.com/ros2/demos/) is (semi) functional (`jazzy` branch, `rmw_fastrtps_cpp` rmw) but we need to review some errors occasionally arising in the `[TYPELOOKUP_SERVICE_REPLY_LISTENER] Error registering remote type: TypeIdentifier unknown to TypeObjectRegistry` 
when `talker` and `listener` are launched (it triggers always in the secondly launched executable) making the application to crash.~~
With latest changes and https://github.com/eProsima/Fast-DDS/pull/5181, demos are functional.

~~Preliminar analysis shows that the problem is who registers the types. If the rmw is fast enough to register the types, then the demo works fine. However if the types are registered from the typelookup service first, some of them are missing or incomplete and leads to crash.
In addition, an arguable behavior was also noticed in the `TypeObjectRegistry::register_type_object`. Imagine that the TLS registers an (incomplete, wrong or corrupt) type object for a given type name. Then, the rmw would like to register the typeobject again but instead of making a logic to accept, discard or update the existing type object in the registry, the typeidentifiers and are instead removed from the collections. This behavior could be reviewed although it most probably be a thing to be taken into consideration apart from the real fix, as it would mitigate the "consequence" instead of the root cause of the problem, probably lying in the TypeLookup service instead.~~  

Addressed in https://github.com/eProsima/Fast-DDS/pull/5181

~~Finally, not all TODOs were address, but theoretically the remaining ones not affecting the core behavior.~~

2024-08-30 11:16 UTC, richiware requested changes
Partial review. Pending `TypeSupport_impl.cpp` to be reviewed.

2024-09-02 06:03 UTC, richiware requested changes

2024-09-02 06:03 UTC, richiware commented on rmw_fastrtps_shared_cpp/src/TypeSupport_impl.cpp
> +    // TODO(richiware) is the name set here in TypeSupport in ROS2? check.
This `TODO` can be removed. I checked it.

2024-09-02 08:27 UTC, richiware requested changes
`cpplint` fails

2024-09-03 07:22 UTC, Mario-DL commented on rmw_fastrtps_cpp/package.xml
>    <build_depend>fastrtps_cmake_module</build_depend>
As we internally agree we will rename it when we unify the rmws in a followup

2024-09-03 07:22 UTC, Mario-DL commented on rmw_fastrtps_cpp/rmw_fastrtps_cpp-extras.cmake
> +list(APPEND rmw_fastrtps_cpp_INCLUDE_DIRS ${FAST_INCLUDE_DIR})
As we internally agree we will rename it when we unify the rmws in a followup

2024-09-05 10:14 UTC, richiware approved these changes

2024-09-05 10:29 UTC, merged