[21569] Support for Topic Keys (vulcanexus-jazzy)
eProsima/rmw_fastrtps pull request #33
Opened 2024-09-04 14:58 UTC by Mario-DL

This PR adds topic instances support for `vulcanexus-jazzy`. 

**IMPORTANT NOTE**
This PR must be merged after 
* #32

2024-09-06 09:33 UTC, MiguelCompany requested changes

2024-09-06 09:33 UTC, MiguelCompany commented on rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/TypeSupport.hpp
> +  mutable eprosima::fastdds::MD5 md5_;
Include the header for MD5

2024-09-06 09:33 UTC, MiguelCompany commented on rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/TypeSupport.hpp
>      return false;
Add a comment indicating why this method can always return false.

2024-09-06 09:33 UTC, MiguelCompany commented on rmw_fastrtps_shared_cpp/src/TypeSupport_impl.cpp
> +        // We would need a get_key_hash_from_payload method
We now have this method. Perhaps we could call it.

2024-09-09 13:25 UTC, JesusPoderoso approved these changes
LGTM

2024-09-09 14:03 UTC, MiguelCompany approved these changes

2024-09-09 14:03 UTC, merged