Fix registration of arrays and sequences
eProsima/rmw_fastrtps pull request #38
Opened 2024-10-22 08:49 UTC by juanlofer-eprosima

Currently arrays are registered as unbounded sequences, and the bounded sequence case is missing. The present PR fixes this behavior.

2024-10-23 11:00 UTC, richiware requested changes

2024-10-23 11:00 UTC, richiware commented on rmw_fastrtps_shared_cpp/src/TypeSupport_impl.cpp
> +            EK_COMPLETE};
```suggestion
            ::EK_COMPLETE};
```

2024-11-19 12:00 UTC, MiguelCompany requested changes
Could we add a test for this?

2024-11-20 13:07 UTC, MiguelCompany approved these changes

2024-11-20 13:07 UTC, merged